#!/usr/bin/env python3
"""jgx_gen.py -- JGX interface generator (design sec 6).

Reads a kernel spec (kernels/specs/<kernel>.yaml) and emits the six committed
artifacts into kernels/generated/:

  1. <kernel>_iface.f90       ISO_C_BINDING args type + launcher interface (L1)
  2. <kernel>_wrapper.f90     jgx_buf -> desc, fill args struct, call C (L1->L2)
  3. <kernel>_args.h          POD args struct shared by all backend launchers
  4. <kernel>_pack.f90        AoS<->SoA pack/unpack for the declared schemas
  5. <kernel>_dispatch.F90    compile-time backend dispatch shell
  6. <kernel>_abi_check.{f90,cpp}  struct size cross-check

No third-party deps (no PyYAML/jinja2): a tiny parser handles the controlled
YAML subset, templates are plain strings. Output is deterministic, so
regenerating over committed files produces zero diff (design sec 8.2).
"""
import sys, os

AUTOGEN = "AUTOGENERATED by tools/jgx_gen.py -- edit the YAML, not this file."

# ---- type maps -----------------------------------------------------------
F_KIND   = {"f64": "real(c_double)", "f32": "real(c_float)",
            "i32": "integer(c_int32_t)", "i64": "integer(c_int64_t)"}
C_TYPE   = {"f64": "double", "f32": "float", "i32": "int32_t", "i64": "int64_t"}
KIND_TAG = {"f64": "JGX_F64", "f32": "JGX_F32", "i32": "JGX_I32", "i64": "JGX_I64"}
F_LOCAL  = {"f64": "real(r64)", "f32": "real(r32)",
            "i32": "integer(i32)", "i64": "integer(i64)"}


# ---- minimal YAML-subset parser -----------------------------------------
def parse_flow(s):
    """Parse a flow mapping '{ k: v, k: v }' into a dict of strings."""
    s = s.strip()
    assert s.startswith("{") and s.endswith("}"), "expected flow map: " + s
    d = {}
    for part in s[1:-1].split(","):
        part = part.strip()
        if not part:
            continue
        k, v = part.split(":", 1)
        d[k.strip()] = v.strip()
    return d


def parse_spec(text):
    spec = {"name": None, "schemas": {}, "buffers": [], "scalars": []}
    section = None
    cur_schema = None
    for raw in text.splitlines():
        line = raw.split("#", 1)[0].rstrip()   # '#' never appears in our values
        if not line.strip():
            continue
        indent = len(line) - len(line.lstrip())
        s = line.strip()
        if indent == 0:
            if s.startswith("name:"):
                spec["name"] = s.split(":", 1)[1].strip()
                section = None
            elif s == "schemas:":
                section = "schemas"
            elif s == "buffers:":
                section = "buffers"
            elif s == "scalars:":
                section = "scalars"
            else:
                raise ValueError("unexpected top-level line: " + s)
        else:
            if section == "schemas":
                if s.startswith("-"):
                    spec["schemas"][cur_schema].append(parse_flow(s[1:].strip()))
                elif s.endswith(":"):
                    cur_schema = s[:-1].strip()
                    spec["schemas"][cur_schema] = []
            elif section == "buffers" and s.startswith("-"):
                spec["buffers"].append(parse_flow(s[1:].strip()))
            elif section == "scalars" and s.startswith("-"):
                spec["scalars"].append(parse_flow(s[1:].strip()))
    return spec


# ---- derived views over the spec ----------------------------------------
def buffer_list(spec):
    """Ordered list of (name, type) for every jgx_buf_desc in the args struct:
    schema fields (as SoA buffers) first, then declared buffers."""
    out = []
    for sname, fields in spec["schemas"].items():
        for f in fields:
            out.append((f["field"], f["type"]))
    for b in spec["buffers"]:
        out.append((b["name"], b["type"]))
    return out


def scalar_list(spec):
    return [(s["name"], s["type"]) for s in spec["scalars"]]


# ---- emitters ------------------------------------------------------------
def emit_args_h(spec):
    name = spec["name"]
    guard = name.upper() + "_ARGS_H"
    lines = [
        "/* {} */".format(AUTOGEN),
        "#ifndef " + guard,
        "#define " + guard,
        "",
        '#include "jgx/jgx_c_api.h"',
        "",
        "#ifdef __cplusplus",
        'extern "C" {',
        "#endif",
        "",
        "typedef struct {",
    ]
    for bname, _ in buffer_list(spec):
        lines.append("  jgx_buf_desc {};".format(bname))
    for sname, stype in scalar_list(spec):
        lines.append("  {:<8} {};".format(C_TYPE[stype], sname))
    lines += [
        "}} {}_args;".format(name),
        "",
        "/* Every backend exports this same symbol; CMake links exactly one. */",
        "void jgx_launch_{}(const {}_args* a);".format(name, name),
        "",
        "#ifdef __cplusplus",
        "}",
        "#endif",
        "",
        "#endif /* {} */".format(guard),
        "",
    ]
    return "\n".join(lines)


def emit_iface_f90(spec):
    name = spec["name"]
    lines = [
        "!> {}".format(AUTOGEN),
        "!! ISO_C_BINDING args type + launcher interface (design sec 6 artifact 1).",
        "module kern_{}_iface".format(name),
        "  use, intrinsic :: iso_c_binding",
        "  use jgx_types, only: jgx_buf_desc",
        "  implicit none",
        "  public",
        "",
        "  type, bind(C) :: {}_args_c".format(name),
    ]
    for bname, _ in buffer_list(spec):
        lines.append("    type(jgx_buf_desc) :: {}".format(bname))
    for sname, stype in scalar_list(spec):
        lines.append("    {} :: {}".format(F_KIND[stype], sname))
    lines += [
        "  end type {}_args_c".format(name),
        "",
        "  interface",
        '    subroutine jgx_launch_{0}_c(a) bind(C, name="jgx_launch_{0}")'.format(name),
        "      import :: {}_args_c".format(name),
        "      type({}_args_c), intent(in) :: a".format(name),
        "    end subroutine jgx_launch_{}_c".format(name),
        "  end interface",
        "",
        "end module kern_{}_iface".format(name),
        "",
    ]
    return "\n".join(lines)


def emit_wrapper_f90(spec):
    name = spec["name"]
    bufs = buffer_list(spec)
    buf_args = ", ".join(b + "_buf" for b, _ in bufs)
    lines = [
        "!> {}".format(AUTOGEN),
        "!! Unpack jgx_buf -> desc, fill the args struct, call the C launcher",
        "!! (design sec 6 artifact 2).",
        "module kern_{}_cwrap".format(name),
        "  use, intrinsic :: iso_c_binding",
        "  use jgx_types, only: jgx_buf, jgx_buf_to_desc",
        "  use kern_{}_iface".format(name),
        "  use kern_particle_push, only: push_params",
        "  implicit none",
        "  private",
        "  public :: {}_launch_c".format(name),
        "contains",
        "",
        "  subroutine {}_launch_c({}, prm)".format(name, buf_args),
        "    type(jgx_buf), intent(inout) :: " + ", ".join(b + "_buf" for b, _ in bufs),
        "    type(push_params), intent(in) :: prm",
        "    type({}_args_c) :: a".format(name),
    ]
    for bname, _ in bufs:
        lines.append("    a%{0} = jgx_buf_to_desc({0}_buf)".format(bname))
    for sname, stype in scalar_list(spec):
        if stype.startswith("i"):
            lines.append("    a%{0} = int(prm%{0}, c_int32_t)".format(sname))
        else:
            lines.append("    a%{0} = prm%{0}".format(sname))
    lines += [
        "    call jgx_launch_{}_c(a)".format(name),
        "  end subroutine {}_launch_c".format(name),
        "",
        "end module kern_{}_cwrap".format(name),
        "",
    ]
    return "\n".join(lines)


def emit_dispatch_f90(spec):
    name = spec["name"]
    bufs = buffer_list(spec)
    buf_args = ", ".join(b + "_buf" for b, _ in bufs)
    up = name.upper()
    # per-buffer c_f_pointer shape expressions for the CPU branch
    def shape_of(bname):
        for b in spec["buffers"]:
            if b["name"] == bname:
                r = int(b["rank"])
                # mesh buffers: shapes are known from scalars by convention
                shapes = {
                    "nl_values": "[prm%nnodes, prm%ndeg, prm%nvar]",
                    "el_vertex": "[4, prm%nelem]",
                    "el_neigh":  "[4, prm%nelem]",
                    "el_origin": "[2, prm%nelem]",
                    "feedback":  "[prm%nelem, prm%nvar, 4]",
                }
                return shapes[bname]
        # schema SoA field
        for _, fields in spec["schemas"].items():
            for f in fields:
                if f["field"] == bname:
                    c = int(f["comps"])
                    return "[prm%npart, {}]".format(c) if c > 1 else "[prm%npart]"
        raise KeyError(bname)

    def ftype(bname):
        for b in spec["buffers"]:
            if b["name"] == bname:
                return F_LOCAL[b["type"]]
        for _, fields in spec["schemas"].items():
            for f in fields:
                if f["field"] == bname:
                    return F_LOCAL[f["type"]]

    def frank(bname):
        for b in spec["buffers"]:
            if b["name"] == bname:
                return int(b["rank"])
        for _, fields in spec["schemas"].items():
            for f in fields:
                if f["field"] == bname:
                    return 2 if int(f["comps"]) > 1 else 1

    lines = [
        "!> {}".format(AUTOGEN),
        "!! Compile-time backend dispatch shell (design sec 2.3, sec 6 artifact 5).",
        "!! Physics always calls {}_dispatch(...); never a backend symbol.".format(name),
        "module kern_{}_dispatch".format(name),
        "  use, intrinsic :: iso_c_binding",
        "  use jgx_kinds",
        "  use jgx_types",
        "  use kern_particle_push, only: push_params",
        "  implicit none",
        "  private",
        "  public :: {}_dispatch".format(name),
        "contains",
        "",
        "  subroutine {}_dispatch({}, prm)".format(name, buf_args),
        "    type(jgx_buf), intent(inout) :: " + ", ".join(b + "_buf" for b, _ in bufs),
        "    type(push_params), intent(in) :: prm",
        "",
        "#if defined(JGX_BACKEND_CPU)",
        "    call dispatch_cpu()",
        "#elif defined(JGX_BACKEND_SERIAL_CPP) || defined(JGX_BACKEND_CUDA) \\",
        "   || defined(JGX_BACKEND_HIP) || defined(JGX_BACKEND_KOKKOS)",
        "    call dispatch_c()",
        "#else",
        '#error "No JGX_BACKEND_* selected for {} dispatch"'.format(name),
        "#endif",
        "",
        "  contains",
        "",
        "#if defined(JGX_BACKEND_CPU)",
        "    subroutine dispatch_cpu()",
        "      use kern_particle_push, only: particle_push_cpu",
    ]
    # pointer declarations
    for bname, _ in bufs:
        r = frank(bname)
        dims = ":" + ",:" * (r - 1)
        lines.append("      {}, pointer :: {}({})".format(ftype(bname), bname, dims))
    for bname, _ in bufs:
        lines.append("      call c_f_pointer({0}_buf%host_ptr, {0}, {1})".format(
            bname, shape_of(bname)))
    call_args = ", ".join(b for b, _ in bufs)
    lines += [
        "      call particle_push_cpu({}, prm)".format(call_args),
        "    end subroutine dispatch_cpu",
        "#else",
        "    subroutine dispatch_c()",
        "      use kern_{}_cwrap, only: {}_launch_c".format(name, name),
        "      call {}_launch_c({}, prm)".format(name, buf_args),
        "    end subroutine dispatch_c",
        "#endif",
        "",
        "  end subroutine {}_dispatch".format(name),
        "",
        "end module kern_{}_dispatch".format(name),
        "",
    ]
    return "\n".join(lines)


def emit_pack_f90(spec):
    name = spec["name"]
    lines = [
        "!> {}".format(AUTOGEN),
        "!! AoS<->SoA pack/unpack for the declared particle schema (design sec 4.4,",
        "!! sec 6 artifact 4). The schema derived type is emitted here so the host",
        "!! declares particle fields once, in the YAML.",
        "module kern_{}_pack".format(name),
        "  use jgx_kinds",
        "  implicit none",
        "  private",
    ]
    for sname, fields in spec["schemas"].items():
        tname = "{}_{}_t".format(name, sname)
        lines.append("  public :: {}".format(tname))
        lines.append("  public :: jgx_pack_{0}, jgx_unpack_{0}".format(sname))
    lines.append("")
    # schema AoS types
    for sname, fields in spec["schemas"].items():
        tname = "{}_{}_t".format(name, sname)
        lines.append("  type :: {}".format(tname))
        for f in fields:
            c = int(f["comps"])
            decl = F_LOCAL[f["type"]]
            if c > 1:
                lines.append("    {} :: {}({})".format(decl, f["field"], c))
            else:
                lines.append("    {} :: {}".format(decl, f["field"]))
        lines.append("  end type {}".format(tname))
        lines.append("")
    lines.append("contains")
    lines.append("")
    for sname, fields in spec["schemas"].items():
        tname = "{}_{}_t".format(name, sname)
        soa_args = ", ".join(f["field"] for f in fields)
        # pack: AoS -> SoA
        lines.append("  subroutine jgx_pack_{}(n, aos, {})".format(sname, soa_args))
        lines.append("    integer, intent(in) :: n")
        lines.append("    type({}), intent(in) :: aos(:)".format(tname))
        for f in fields:
            c = int(f["comps"])
            dims = "(:,:)" if c > 1 else "(:)"
            lines.append("    {}, intent(out) :: {}{}".format(F_LOCAL[f["type"]], f["field"], dims))
        lines.append("    integer :: j, c")
        lines.append("    do j = 1, n")
        for f in fields:
            c = int(f["comps"])
            if c > 1:
                lines.append("      do c = 1, {}".format(c))
                lines.append("        {0}(j,c) = aos(j)%{0}(c)".format(f["field"]))
                lines.append("      end do")
            else:
                lines.append("      {0}(j) = aos(j)%{0}".format(f["field"]))
        lines.append("    end do")
        lines.append("  end subroutine jgx_pack_{}".format(sname))
        lines.append("")
        # unpack: SoA -> AoS
        lines.append("  subroutine jgx_unpack_{}(n, aos, {})".format(sname, soa_args))
        lines.append("    integer, intent(in) :: n")
        lines.append("    type({}), intent(inout) :: aos(:)".format(tname))
        for f in fields:
            c = int(f["comps"])
            dims = "(:,:)" if c > 1 else "(:)"
            lines.append("    {}, intent(in) :: {}{}".format(F_LOCAL[f["type"]], f["field"], dims))
        lines.append("    integer :: j, c")
        lines.append("    do j = 1, n")
        for f in fields:
            c = int(f["comps"])
            if c > 1:
                lines.append("      do c = 1, {}".format(c))
                lines.append("        aos(j)%{0}(c) = {0}(j,c)".format(f["field"]))
                lines.append("      end do")
            else:
                lines.append("      aos(j)%{0} = {0}(j)".format(f["field"]))
        lines.append("    end do")
        lines.append("  end subroutine jgx_unpack_{}".format(sname))
        lines.append("")
    lines.append("end module kern_{}_pack".format(name))
    lines.append("")
    return "\n".join(lines)


def emit_abi_check_cpp(spec):
    name = spec["name"]
    lines = [
        "/* {} */".format(AUTOGEN),
        "/* ABI cross-check: expose the struct sizes to the Fortran side and",
        "   static_assert the descriptor is standard-layout (design sec 4.6). */",
        '#include "kernels/generated/{}_args.h"'.format(name),
        "#include <cstddef>",
        "#include <type_traits>",
        "",
        "static_assert(std::is_standard_layout<jgx_buf_desc>::value,",
        '              "jgx_buf_desc must be standard-layout");',
        "static_assert(std::is_standard_layout<{}_args>::value,".format(name),
        '              "{}_args must be standard-layout");'.format(name),
        "",
        'extern "C" size_t jgx_c_sizeof_{}_args(void) {{'.format(name),
        "  return sizeof({}_args);".format(name),
        "}",
        "",
    ]
    return "\n".join(lines)


def emit_abi_check_f90(spec):
    name = spec["name"]
    lines = [
        "!> {}".format(AUTOGEN),
        "!! ABI cross-check: compare the Fortran bind(C) args size against the C",
        "!! sizeof (design sec 4.6, sec 8.2 test).",
        "module kern_{}_abi_check".format(name),
        "  use, intrinsic :: iso_c_binding",
        "  use kern_{}_iface, only: {}_args_c".format(name, name),
        "  implicit none",
        "  private",
        "  public :: {}_abi_ok".format(name),
        "  interface",
        '    function c_sizeof_args() bind(C, name="jgx_c_sizeof_{}_args") result(n)'.format(name),
        "      import :: c_size_t",
        "      integer(c_size_t) :: n",
        "    end function c_sizeof_args",
        "  end interface",
        "contains",
        "  logical function {}_abi_ok()".format(name),
        "    type({}_args_c) :: a".format(name),
        "    {}_abi_ok = (c_sizeof(a) == c_sizeof_args())".format(name),
        "  end function {}_abi_ok".format(name),
        "end module kern_{}_abi_check".format(name),
        "",
    ]
    return "\n".join(lines)


# ---- driver --------------------------------------------------------------
def main():
    if len(sys.argv) != 2:
        sys.exit("usage: jgx_gen.py <spec.yaml>")
    spec_path = sys.argv[1]
    with open(spec_path) as f:
        spec = parse_spec(f.read())
    name = spec["name"]
    # spec lives in kernels/specs/ ; generated files go in the sibling
    # kernels/generated/. project root is two levels up from the spec dir.
    kernels_dir = os.path.dirname(os.path.dirname(os.path.abspath(spec_path)))
    root = os.path.dirname(kernels_dir)
    outdir = os.path.join(kernels_dir, "generated")
    os.makedirs(outdir, exist_ok=True)

    artifacts = {
        "{}_args.h".format(name):          emit_args_h(spec),
        "{}_iface.f90".format(name):       emit_iface_f90(spec),
        "{}_wrapper.f90".format(name):     emit_wrapper_f90(spec),
        "{}_pack.f90".format(name):        emit_pack_f90(spec),
        "{}_dispatch.F90".format(name):    emit_dispatch_f90(spec),
        "{}_abi_check.cpp".format(name):   emit_abi_check_cpp(spec),
        "{}_abi_check.f90".format(name):   emit_abi_check_f90(spec),
    }
    for fname, content in sorted(artifacts.items()):
        path = os.path.join(outdir, fname)
        with open(path, "w") as f:
            f.write(content)
        print("wrote", os.path.relpath(path, root))


if __name__ == "__main__":
    main()
