# Print what was actually configured. The Make build had `make printsettings`
# for this; here it comes for free at the end of every configure.

string(REPLACE ";" " " _defines_pretty "${JOREK_DEFINES}")

message(STATUS "")
message(STATUS "==================== JOREK configuration ====================")
message(STATUS "  Model             : ${JOREK_MODEL} (number ${JOREK_MODEL_NUMBER})")
message(STATUS "  Build type        : ${CMAKE_BUILD_TYPE}")
message(STATUS "  Executable        : jorek_model${JOREK_MODEL_NUMBER}")
message(STATUS "  Fortran compiler  : ${CMAKE_Fortran_COMPILER} (${CMAKE_Fortran_COMPILER_ID})")
message(STATUS "  C / C++ compiler  : ${CMAKE_C_COMPILER_ID} / ${CMAKE_CXX_COMPILER_ID}")
message(STATUS "  MPI               : ${MPI_Fortran_VERSION}")
if(JGX_DEVICE STREQUAL "off")
  message(STATUS "  JGX device        : off (host only)")
elseif(JGX_DEVICE_AMD_ARCH)
  message(STATUS "  JGX device        : ${JGX_DEVICE} (${JGX_DEVICE_ARCH}), "
                 "compiled as ${CMAKE_HIP_COMPILER_ID} HIP ${CMAKE_HIP_COMPILER_VERSION}")
else()
  message(STATUS "  JGX device        : ${JGX_DEVICE} (${JGX_DEVICE_ARCH}), "
                 "compiled as ${CMAKE_CUDA_COMPILER_ID} CUDA ${CMAKE_CUDA_COMPILER_VERSION}")
endif()
message(STATUS "  BLAS/LAPACK       : ${JOREK_BLAS_LAPACK_SUMMARY}")
if(JOREK_USE_HDF5)
  message(STATUS "  HDF5              : ${JOREK_HDF5_SUMMARY}")
endif()
if(JOREK_USE_FFTW)
  message(STATUS "  FFTW              : ${JOREK_FFTW_SUMMARY}")
endif()
if(JOREK_USE_STRUMPACK)
  message(STATUS "  STRUMPACK         : ${JOREK_STRUMPACK_LIBRARY}")
endif()
if(JOREK_USE_MUMPS)
  message(STATUS "  MUMPS             : ${JOREK_DMUMPS_LIBRARY}")
endif()
if(JOREK_USE_PASTIX OR JOREK_USE_PASTIX6)
  message(STATUS "  PaStiX            : ${JOREK_PASTIX_LIBRARY}")
endif()
message(STATUS "  Defines           : ${_defines_pretty}")
message(STATUS "============================================================")
message(STATUS "")
